  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
 
    <script type="text/javascript">

      
      
      google.load('visualization', '1.0', {'packages':['corechart']});
	</script>
<script>
	javascript:THREEx.Screenshot.bindKey(renderer);
</script>
<h4>Usage Datapool Statistics</h4>
<div id="usagestats" style="border-style: 2px dotted green;border-color:green;background-color:black;color:green;">
	<strong>UserHasLoggedandAction:</strong> <?echo $this->stats['hasloggedandAction']?> / <? echo $this->infodp->usernumber?><br/>
	<strong>UserHasLogged:</strong> <?echo $this->stats['hasloggedcount']?> / <? echo $this->infodp->usernumber?><br/>
	<p style="font-size:11px;color:yellow;">UserHasLoggedandAction : Users that has logged in and make some modification on profile section</p>
	
</div>
<div style="height:10px;"></div>
<h4>Scenario Statistics</h4>
<div id="datapooltypestats" style="border-style: 2px dotted green;border-color:green;background-color:black;color:green;">
	<strong>LoginTimeAvg:</strong> <?echo $this->stats['avgspeedlogin']?> seconds<br/>
	<p style="font-size:11px;color:yellow;">LoginTimeAvg: Time passed between customer_session_init and customer_login events</p>
</div>
<script>			
 google.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');
        data.addRows([
          ['UserHasLoggedandAction',<?echo $this->stats['hasloggedandAction']?>],
          ['UserHasLogged',<?echo $this->stats['hasloggedcount']?> ],
          ['NotUsed',<?echo $this->infodp->usernumber - $this->stats['hasloggedcount']?> ],
        ]);

        // Set chart options
        var options = {'title':'Datapool Usage Resource',
                       'width':400,
                       'height':300};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div_datapool_usage'));
        chart.draw(data, options);
      }
    </script>



<script>
 google.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Datapool Name', 'Login Time Avg'],
          ['<?php echo $this->infodp->name ?>', <?php echo $this->stats['avgspeedlogin']?>] 
        ]);

        var options = {
          title: 'Avg Login Time',
          vAxis: {title: 'Datapool',  titleTextStyle: {color: 'red'}}
        };

        var chart = new google.visualization.BarChart(document.getElementById('chart_div_datapool_login_speedavg'));
        chart.draw(data, options);
      }

    </script>


<div style="float:left;">
<div id="chart_div_datapool_usage"  ></div>
</div>
<div style="float:left;">
<div id="chart_div_datapool_login_speedavg"></div>
</div>